Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/new'
  get 'posts/create'
  get 'subs/new'
  get 'subs/create'
  get 'subs/edit'
  get 'subs/update'
  get 'subs/show'
  get 'subs/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
